date_collector_task:
  description: >
    Get the correct date from the user's input: '{user_input}'. If year is missing, ask the user. Use the provided conversation history {context} 
  expected_output: >
    "A confirmed date in YYYY-MM-DD format or YYYY-MM-DD to YYYY-MM-DD format"

transcript_collection_task:
  description: >
    Retrieve and process daily standup transcripts from Google Cloud Storage for a specified date or date range.
    Skip files that have already been processed. Clean, deduplicate, and store cleaned transcripts to a processed path.
  expected_output: >
    A structured summary of which files were processed and which were skipped due to prior processing.
    Cleaned transcripts will be stored in GCS under the processed prefix, organized by date.

data_validation_task:
  description: >
    Check if data is missing. If we dont have any data, it means nothing is available. You need to inform the user that the given date has no available data.
  expected_output: >
    A structured summary of files content if anything is available otherwise just a note to user that the data is not available.

report_generation_task:
    description: >
      - Process the output generated by the transcript collector
      - Analyze individual user progress and extract key insights
      - Compile individual reports for each user, including tasks completed, areas of focus, and next steps
      - Send and email including the daily reports to the project manager for review and action. In this email give a proper 
        subject and organize the body properly. Start with introducing yourself as a Project Manager Agent Asistant and then 
        give them the report and finish the email respectfully.
     
    expected_output: >
      inform the user that the report will be sent to their email shortly.

 # - Maintain a repository for all reports (both daily and monthly)
      # - Ensure the reports are correctly stored for long-term access
      # - Create monthly summaries based on the daily reports, highlighting trends and key actions
  # input_parameters: 
  #   - date_or_range: "A single date (e.g., '2025-03-27') or a date range (e.g., '2025-03-25 to 2025-03-27')"
  #   - bucket_name: "The name of the GCS bucket"
  #   - raw_prefix: "Prefix path in GCS where raw transcripts are stored"
  #   - processed_prefix: "Prefix path in GCS where cleaned transcripts will be stored"